const KEY="bang_luong_offline_v2";
const defaults={settings:{baseSalary:4500000,standardDays:26,allowance:1000000,cnRate:10,tvRate:7},employees:[{id:crypto.randomUUID(),name:"Hậu",active:true}],attendance:[]};
let data=load(), deferredInstall=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat("vi-VN",{maximumFractionDigits:0}).format(Number(n)||0)+" ₫";
const now=new Date(), monthNow=()=>`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,"0")}`;
const weekdays=["Chủ Nhật","Thứ Hai","Thứ Ba","Thứ Tư","Thứ Năm","Thứ Sáu","Thứ Bảy"];
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));return x||structuredClone(defaults)}catch{return structuredClone(defaults)}}
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
function toast(s){const t=$("#toast");t.textContent=s;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),1800)}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function employeeName(id){return data.employees.find(e=>e.id===id)?.name||"—"}
function calc(a){return {...a,cnPct:(+a.cn||0)*data.settings.cnRate/100,tvPct:(+a.tv||0)*data.settings.tvRate/100}}
function rows(month,emp=""){return data.attendance.filter(a=>a.date?.startsWith(month)&&(!emp||a.employeeId===emp)).map(calc).sort((a,b)=>a.date.localeCompare(b.date))}
function salary(month,emp=""){const r=rows(month,emp),days=r.filter(x=>x.work).length,cn=r.reduce((s,x)=>s+(+x.cn||0),0),tv=r.reduce((s,x)=>s+(+x.tv||0),0),p10=r.reduce((s,x)=>s+x.cnPct,0),p7=r.reduce((s,x)=>s+x.tvPct,0),db=data.settings.baseSalary/data.settings.standardDays,da=data.settings.allowance/data.settings.standardDays;return{r,days,cn,tv,p10,p7,pct:p10+p7,base:days*db,allowance:days*da,total:days*(db+da)+p10+p7}}
function showPage(p){$(".page.active")?.classList.remove("active");$("#"+p).classList.add("active");$$(".nav-btn").forEach(b=>b.classList.toggle("active",b.dataset.page===p));renderAll()}
function renderAll(){const m=$("#dashboardMonth").value||monthNow(),s=salary(m);$("#monthLabel").textContent=`Tháng ${m.slice(5,7)}/${m.slice(0,4)}`;$("#statDays").textContent=s.days;$("#statCN").textContent=money(s.cn);$("#statTV").textContent=money(s.tv);$("#statPct").textContent=money(s.pct);$("#statSalary").textContent=money(s.total);renderOptions();renderAttendance();renderPayroll();renderEmployees();renderSettings()}
function renderOptions(){const a=$("#attendanceEmployee"),p=$("#payrollEmployee"),av=a.value,pv=p.value;a.innerHTML='<option value="">Tất cả nhân viên</option>'+data.employees.filter(e=>e.active).map(e=>`<option value="${e.id}">${esc(e.name)}</option>`).join("");p.innerHTML=data.employees.map(e=>`<option value="${e.id}">${esc(e.name)}</option>`).join("");if(data.employees.some(e=>e.id===av))a.value=av;if(data.employees.some(e=>e.id===pv))p.value=pv;else if(data.employees[0])p.value=data.employees[0].id}
function fmt(d){const [y,m,day]=d.split("-");return `${day}/${m}/${y}`}
function renderAttendance(){const m=$("#attendanceMonth").value||monthNow(),emp=$("#attendanceEmployee").value,r=rows(m,emp);$("#attendanceBody").innerHTML=r.length?r.map(a=>`<tr><td>${fmt(a.date)}</td><td>${weekdays[new Date(a.date+"T00:00:00").getDay()]}</td><td>${esc(employeeName(a.employeeId))}</td><td><input type="checkbox" ${a.work?"checked":""} onchange="toggleWork('${a.id}',this.checked)"></td><td>${money(a.cn)}</td><td>${money(a.tv)}</td><td>${money(a.cnPct)}</td><td>${money(a.tvPct)}</td><td><b>${money(a.cnPct+a.tvPct)}</b></td><td><button onclick="editAttendance('${a.id}')">✎</button> <button onclick="deleteAttendance('${a.id}')">🗑</button></td></tr>`).join(""):`<tr><td colspan="10" class="empty">Chưa có dữ liệu. Bấm “＋ Thêm”.</td></tr>`}
function renderPayroll(){const m=$("#payrollMonth").value||monthNow(),emp=$("#payrollEmployee").value||data.employees[0]?.id,s=salary(m,emp);$("#payrollSummary").innerHTML=[["Ngày công",s.days+" ngày"],["Lương cơ bản",money(s.base)],["Phụ cấp",money(s.allowance)],["Doanh thu VS CN",money(s.cn)],["Doanh thu VS TV",money(s.tv)],["Tiền 10%",money(s.p10)],["Tiền 7%",money(s.p7)],["Tổng tiền %",money(s.pct)],["TỔNG LƯƠNG",money(s.total)]].map((x,i)=>`<div class="pay-card ${i===8?"total":""}"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join("");$("#payrollBody").innerHTML=s.r.length?s.r.map(a=>`<tr><td>${fmt(a.date)}</td><td>${a.work?"Có":"Không"}</td><td>${money(a.cn)}</td><td>${money(a.tv)}</td><td>${money(a.cnPct+a.tvPct)}</td></tr>`).join(""):`<tr><td colspan="5" class="empty">Chưa có dữ liệu.</td></tr>`}
function renderEmployees(){$("#employeeList").innerHTML=data.employees.length?data.employees.map(e=>`<div class="employee"><div><b>${esc(e.name)}</b><small>${e.active?"Đang làm":"Đã nghỉ"}</small></div><div class="employee-actions"><button onclick="editEmployee('${e.id}')">Sửa</button><button onclick="deleteEmployee('${e.id}')">Xóa</button></div></div>`).join(""):"<div class='card'>Chưa có nhân viên.</div>"}
function renderSettings(){const s=data.settings;$("#baseSalary").value=s.baseSalary;$("#standardDays").value=s.standardDays;$("#allowance").value=s.allowance;$("#cnRate").value=s.cnRate;$("#tvRate").value=s.tvRate}
function openModal(title,html){$("#modalTitle").textContent=title;$("#modalContent").innerHTML=html;$("#modal").classList.remove("hidden")}
function closeModal(){$("#modal").classList.add("hidden")}
function attendanceForm(id=""){const a=data.attendance.find(x=>x.id===id)||{date:$("#attendanceMonth").value?$("#attendanceMonth").value+"-01":now.toISOString().slice(0,10),employeeId:data.employees[0]?.id||"",work:true,cn:0,tv:0};openModal(id?"Sửa chấm công":"Thêm chấm công",`<form class="modal-form" id="attForm"><label>Ngày<input id="fDate" type="date" required value="${a.date}"></label><label>Nhân viên<select id="fEmp" required>${data.employees.map(e=>`<option value="${e.id}" ${e.id===a.employeeId?"selected":""}>${esc(e.name)}</option>`).join("")}</select></label><label><input id="fWork" type="checkbox" ${a.work?"checked":""}> Đi làm</label><label>VS công nghiệp<input id="fCN" type="number" min="0" step="1000" value="${a.cn||0}"></label><label>VS tạp vụ<input id="fTV" type="number" min="0" step="1000" value="${a.tv||0}"></label><div class="modal-actions"><button class="primary" type="submit">Lưu</button><button type="button" onclick="closeModal()">Hủy</button></div></form>`);$("#attForm").onsubmit=e=>{e.preventDefault();const o={id:id||crypto.randomUUID(),date:$("#fDate").value,employeeId:$("#fEmp").value,work:$("#fWork").checked,cn:+$("#fCN").value||0,tv:+$("#fTV").value||0};if(id)data.attendance[data.attendance.findIndex(x=>x.id===id)]=o;else data.attendance.push(o);save();closeModal();renderAll();toast("Đã lưu chấm công")}}
window.editAttendance=attendanceForm;window.toggleWork=(id,v)=>{const a=data.attendance.find(x=>x.id===id);if(a){a.work=v;save();renderAll()}};window.deleteAttendance=id=>{if(confirm("Xóa bản ghi này?")){data.attendance=data.attendance.filter(x=>x.id!==id);save();renderAll();toast("Đã xóa")}}
function employeeForm(id=""){const e=data.employees.find(x=>x.id===id)||{name:"",active:true};openModal(id?"Sửa nhân viên":"Thêm nhân viên",`<form class="modal-form" id="empForm"><label>Tên nhân viên<input id="eName" required value="${esc(e.name)}"></label><label><input id="eActive" type="checkbox" ${e.active?"checked":""}> Đang làm</label><div class="modal-actions"><button class="primary" type="submit">Lưu</button><button type="button" onclick="closeModal()">Hủy</button></div></form>`);$("#empForm").onsubmit=x=>{x.preventDefault();const o={id:id||crypto.randomUUID(),name:$("#eName").value.trim(),active:$("#eActive").checked};if(!o.name)return;if(id)data.employees[data.employees.findIndex(e=>e.id===id)]=o;else data.employees.push(o);save();closeModal();renderAll();toast("Đã lưu nhân viên")}}
window.editEmployee=employeeForm;window.deleteEmployee=id=>{if(confirm("Xóa nhân viên này?")){data.employees=data.employees.filter(e=>e.id!==id);save();renderAll();toast("Đã xóa")}}
function exportData(){const b=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=`bang-luong-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function importData(file){const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!x.settings||!Array.isArray(x.employees)||!Array.isArray(x.attendance))throw 0;data=x;save();renderAll();toast("Đã nhập dữ liệu")}catch{alert("File sao lưu không hợp lệ.")}};r.readAsText(file)}
function resetData(){if(confirm("Xóa toàn bộ dữ liệu trên thiết bị? Hãy sao lưu trước.")){localStorage.removeItem(KEY);data=structuredClone(defaults);save();renderAll();toast("Đã đặt lại dữ liệu")}}

window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredInstall=e;$("#installCard").style.display="flex"});
$("#installBtn").onclick=async()=>{if(!deferredInstall){toast("Mở menu trình duyệt và chọn Thêm vào màn hình chính");return}deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null};
window.addEventListener("appinstalled",()=>{$("#installCard").style.display="none";toast("Đã cài ứng dụng")});

document.addEventListener("DOMContentLoaded",()=>{
 ["dashboardMonth","attendanceMonth","payrollMonth"].forEach(id=>$("#"+id).value=monthNow());
 $$(".nav-btn,[data-page]").forEach(b=>b.addEventListener("click",()=>showPage(b.dataset.page)));
 $("#addAttendance").onclick=()=>attendanceForm();$("#addEmployee").onclick=()=>employeeForm();$("#closeModal").onclick=closeModal;$("#modal").onclick=e=>{if(e.target.id==="modal")closeModal()};
 $("#dashboardMonth").onchange=renderAll;$("#attendanceMonth").onchange=renderAttendance;$("#attendanceEmployee").onchange=renderAttendance;$("#payrollMonth").onchange=renderPayroll;$("#payrollEmployee").onchange=renderPayroll;
 $("#settingsForm").onsubmit=e=>{e.preventDefault();data.settings={baseSalary:+$("#baseSalary").value||0,standardDays:+$("#standardDays").value||26,allowance:+$("#allowance").value||0,cnRate:+$("#cnRate").value||0,tvRate:+$("#tvRate").value||0};save();renderAll();toast("Đã lưu cài đặt")};
 $("#exportBtn").onclick=exportData;$("#backupBtn").onclick=exportData;$("#importFile").onchange=e=>e.target.files[0]&&importData(e.target.files[0]);$("#resetBtn").onclick=resetData;renderAll();
});